//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBBackEnd.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int RouteID { get; set; }
        public string NameShort { get; set; }
        public string NameLong { get; set; }
        public string Description { get; set; }
        public System.DateTime dtCreated { get; set; }
    }
}
