//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBBackEnd.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopTime
    {
        public int TripID { get; set; }
        public int StopID { get; set; }
        public string Arrival { get; set; }
        public string Departure { get; set; }
        public Nullable<int> SortID { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtDeparture { get; set; }
    
        public virtual Stop Stop { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
